name: build
on:
  push:
    branches: [master]
  pull_request:
    branches: ['*']
    paths-ignore:
      - 'docs/**'
      - '.vscode/**'
      - 'README.md'
      - '.gitignore'
      - 'LICENSE.txt'
      - 'example'
      - 'CHANGELOG.md'
      - 'NOTICE.md'

jobs:
  main:
    name: 'Main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run format
      - run: bun run lint
      - run: bun run build
      - run: bun test