name: build
on:
  push:
    paths:
      - '.github/workflows/build.yml'
      - 'package.json'
      - 'tsconfig.json'
      - 'tsconfig.types.json'
      - 'src/**/*'
    branches:
      - 'master'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: 'Test & Build'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Clean Project
        run: bun run clean

      - name: Install dependencies
        run: bun install

      - name: check format & lint
        run: bun run format

      - name: Run tests
        run: bun test

      - name: Build project
        run: bun run build

      - name: Check for changes in dist
        id: changes
        run: |
          git add -f ./dist
          if git diff --cached --quiet; then
            echo "no_changes=true" >> $GITHUB_ENV
          else
            echo "no_changes=false" >> $GITHUB_ENV

      - name: Push to GitHub
        if: env.no_changes == 'false'
        uses: EndBug/add-and-commit@v9.1.1
        with:
          add: '-f ./dist'
          author_name: 'GitHub Actions'
          author_email: 'action@github.com'
          message: 'build: Build action'