name: build
on:
  push:
    - '.github/workflows/build.yml'
    - 'src/**/*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: 'Test & Build'
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v4
      uses: oven-sh/setup-bun@v2
      run: bun install
      run: bun run format
      run: bun run lint
      run: bun test
      run: bun run build
      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9.1.1
        with:
          add: '-f ./dist'
          author_name: 'GitHub Actions'
          author_email: 'action@github.com'
          message: 'build: Build action'