name: build
on:
  push:
    branches: [master]
  pull_request:
    branches: ['*']
    paths-ignore:
      - 'docs/**'
      - '.vscode/**'
      - 'README.md'
      - '.gitignore'
      - 'LICENSE.txt'
      - 'example'
      - 'CHANGELOG.md'
      - 'NOTICE.md'

jobs:
  main:
    name: 'Main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check for src changes
        run: |
          if ! git diff --quiet HEAD^ HEAD -- src; then
            echo "Changes detected in 'src'. Proceeding..."
          else
            echo "No changes detected in 'src'. Exiting..."
            exit 0
          fi
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run format
      - run: bun run lint
      - run: bun run build
      - run: bun test

  build:
    name: Push to GitHub
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check for src changes
        run: |
          if ! git diff --quiet HEAD^ HEAD -- src; then
            echo "Changes detected in 'src'. Proceeding..."
          else
            echo "No changes detected in 'src'. Exiting..."
            exit 0
          fi
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run build
      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9.1.1
        with:
          add: '-f ./dist'
          author_name: 'GitHub Actions'
          author_email: 'action@github.com'
          message: 'build: Build action'