name: update changelog

on:
  push:
    paths:
      - 'docs/changelog.json'

jobs:
  main:
    name: 'build & push changelog'
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v4
      uses: oven-sh/setup-bun@v2
      run: bun run changelog
      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9.1.1
        with:
          add: '-f ./docs/CHANGELOG.md'
          author_name: 'GitHub Actions'
          author_email: 'action@github.com'
          message: 'build: Build action'